#ifndef DNAEDITORDIALOG_H
#define DNAEDITORDIALOG_H

#include <QDialog>
#include <QVector>

class QComboBox;
class QSlider;
class QSpinBox;
class SpectrumVisualizer;

/**
 * DNA Editor Dialog - Simple editor for harmonic distribution patterns
 *
 * Simplified version focusing on core functionality:
 * - Sequence dropdown (All, Odd, Even, OddDominant, Fundamental+, Octaves, Custom)
 * - Purity slider (0-100%)
 * - Spectrum preview
 * - OK/Cancel buttons
 */
class DnaEditorDialog : public QDialog
{
    Q_OBJECT

public:
    explicit DnaEditorDialog(int numHarmonics = 64, QWidget *parent = nullptr);
    ~DnaEditorDialog();

    // Get custom DNA pattern generated by the dialog
    QVector<double> getCustomDnaPattern() const { return customPattern; }

    // Set an existing custom pattern (for editing existing custom DNA)
    void setCustomPattern(const QVector<double> &pattern);

private slots:
    void onSequenceChanged(int index);
    void onSaveCustomDna();
    void onLoadCustomDna();

private:
    QComboBox *comboSequence;
    SpectrumVisualizer *spectrumPreview;

    int numHarmonics;
    QVector<double> customPattern;  // Generated harmonic amplitudes

    void updatePattern();
    void generateSequencePattern(int sequenceType);
};

#endif // DNAEDITORDIALOG_H
